### ISSUE TITLE
Geo Addon Required?

### ISSUE THREAD

**Issue by ankerr** [bakercp/ofxTwitter#11]
Trying to make the examples, but getting the error:

/openFrameworks-master/addons/ofxTwitter/libs/ofxTwitter/include/ofx/Twitter/Status.h:14:10: fatal error: 'ofx/Geo/Coordinate.h' file not found

include "ofx/Geo/Coordinate.h"
     ^
1 error generated.
make[1]: *** [obj/osx/Release/src/main.o] Error 1
make: *** [Release] Error 2

Trying adding the master branch copy of ofxGeo into the addons, but no luck.

Am I going wrong somewhere, or is ofxGeo required?

**Comment by bakercp** [comment]
Yes, it's required.

**Comment by ankerr** [comment]
Ahh, just noticed the coordinate filters in stream example. Thanks!
