### ISSUE TITLE
Upload media file as different clients

### ISSUE THREAD

**Issue by ukelady** [bakercp/ofxTwitter#6]
Hi again!
I actually need to upload the files using different account from the one that creates the twitter app. Is there a way to upload data as another user? If I understand it right, I'll need to send user name and pass to twitter api and feed another set of credential to the client object. If this function doesn't exist yet, I would be happy to help implementing it. I just need a bit insight from your side. Thanks!

**Comment by bakercp** [comment]
I'm closing this as a will-not-add, but I'm happy to take pull-requests!
