### ISSUE TITLE
Not finding dependencies

### ISSUE THREAD

**Issue by schnurbert** [bakercp/ofxTwitter#7]
Hi, sorry for bothering, somehow I can't get the examples together,

after missing `ofx/HTTP/OAuth10HTTPClient.h` I added the ofxHTTP Develop Branch,
then json.hpp missed, so I homebrewed `https://github.com/nlohmann/json` and added the search path inside the xcode build settings,
now its complaining about `ofJson.h` missing and I'm getting the feeling that I'm missing something more essential, maybe you can help? 

still thanks for adding me to the repository,
best regards, schnurbert

**Comment by bakercp** [comment]
All addons require the master branch.  OpenFrameworks master branch is required as well.
